In [18]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.text_cell_render.rendered_html{font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size="6" color ="red" > N차원 배열(Numpy 배열) 다루기</font></b>
# 4절 복사와 뷰
## 4.1 할당

In [24]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
b = a

In [31]:
a.shape, a.ndim, id(a), type(a)

((3, 4), 2, 2395313623792, numpy.ndarray)

In [32]:
b.shape, b.ndim, id(b), type(b)

((3, 4), 2, 2395313623792, numpy.ndarray)

In [33]:
a == b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
b.shape = (3,4) # 할당받은 b의 shape를 수정

## 4.2 얕은복사 : 뷰(View)


In [48]:
a = np.arange(12).reshape(3,4)

In [49]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
c = a.view() # 얕은 복사
print(id(a), id(c))

2395313897360 2395314143952


In [51]:
c == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
c.shape = (2,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [54]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
c[0, ::2] = -49 # 1행의 짝수번째 열 변경(9)
c

array([[-49, -99, -49, -99, -49, -99],
       [-99, -99, -99, -99, -99, -99]])

In [58]:
a

array([[  0,   1,   2,   3],
       [  4,   5, -99,   7],
       [-99,   9, -99,  11]])

## 4.3 깊은 복사

In [61]:
a = np.array([[5,5,15,0],
            [60,6,16,1],
            [20,5,16,1]])
a

array([[ 5,  5, 15,  0],
       [60,  6, 16,  1],
       [20,  5, 16,  1]])

In [64]:
X = a[:, :-1] # 슬라이싱이 될 때, 뷰가 반환딤(얕은복사)
X = a[:, :-1].copy() #깊은 복사
X = np.array(a[:,:-1], copy=True) #깊은복사
X

array([[-9,  5, 15],
       [-9,  6, 16],
       [-9,  5, 16]])

In [65]:
X[:, 0] = -9
X

array([[-9,  5, 15],
       [-9,  6, 16],
       [-9,  5, 16]])

# 5절 고급인덱싱
