In [4]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:60% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:22pt;}
div.text_cell_render.rendered_html{font-size:18pt;}
div.text_cell_render ul li{font-size:22pt; line-height:30px;}
div.output {font-size:22pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:22pt;}
div.prompt {min-width:40px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:22pt;padding:5px;}
table.dataframe{font-size:22px;}
</style>
"""))

# 1 tensorflow v2.xx에서 v1 사용하기

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # tensorflow V2 비활성화하고 v1활성화
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


## Tensorflow
- 데이터 흐름 그래프(tensor 객체의 흐름)응 사용하는 수치 계산 라이브러리
- 그래프는 node(연산)와 edge로 구성
- sess = tf.Session()을 이용해서 실행 환경
- sess.run()을 통해서 실행 결과를 확인

In [2]:
# 1단계 : tensor(상수 노드 하나) 정의
node1 = tf.constant('Hello, Tensorflow')
# 2단계 : 세션(연산을 실행하는 환경) 생성
sess = tf.Session()
# 3단계 : 실제 실행;
print(sess.run(node1))
print(sess.run(node1).decode())

b'Hello, Tensorflow'
Hello, Tensorflow


In [90]:
# 간단한 연산 tensor 그래프
# 1. 그래프 정의
node1 = tf.constant(10, dtype=tf.float16)
node2 = tf.constant(20, dtype=tf.float16)
node3 = tf.add(node1, node2)
# 2. 세션 생성
sess = tf.Session()
# 3. 세션 실행 & 결과
print(sess.run([node1, node2, node3]))

[10.0, 20.0, 30.0]


In [ ]:
# 타입변경
import numpy as np
node1 = tf.constant(np.array([1,2,3]), dtype=tf.int16)
node2 = tf.cast(node1, dtype=tf.float32)
sess  = tf.Session()
print(sess.run([node1, node2]))

In [ ]:
# 평균값 계산 : tf.reduce_mean()
data = np.array([1.,2.,3.,4.])
m = tf.reduce_mean(data)
sess = tf.Session()
print(sess.run(m))


In [2]:
# tf.random_normal([size]) : 평균이 0이고 표준편차가 1인 난수 size개 발생
w = tf.random_normal([5])

sess = tf.Session()

sess.run(w)

array([ 0.6240958 , -1.0594398 ,  0.90496516,  1.6272439 , -1.0671234 ],
      dtype=float32)

In [3]:
# 변수 노드
w = tf.Variable(tf.random_normal([1]))
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 변수 초기화
sess.run(w)

array([-0.7844402], dtype=float32)

# 2 tensorflow v1을 이용한 회귀분석 구현
## 2.1 독립변수 x가 1개, 타겟(종속)변수 y가 1개

In [4]:
# tensor 그래프 정의
# 데이터 셋 확보

x = np.array([1,2,3])
y = np.array([2,3,4])
# weight와 bias
W = tf.Variable(tf.random.normal([1]), name = 'weight')
b = tf.Variable(tf.random.normal([1]), name = 'bias')
# Hat, Hypothesis : 결과는 numpy 배열
H = W * x + b
# cost function (손실함수 : mse)
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w, b를 찾는 것
cost 함수는 2차함수이므로 곡선 그래프. 곡선위 미분값이 0이 되는 방향
(경사하강법GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# 세션 생성
sess = tf.Session()
# W,b 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습 (v2 에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b])
    if step%300==0:
        print("{}번째 cost:{}, W:{}, b:{}".format(step, cost_val, W_val, b_val))


0번째 cost:70.54701232910156, W:[-1.6690505], b:[-0.8049144]
300번째 cost:0.00950100552290678, W:[1.1129369], b:[0.74326813]
600번째 cost:0.0022418461740016937, W:[1.0548596], b:[0.87529105]
900번째 cost:0.0005289750988595188, W:[1.0266482], b:[0.9394223]
1200번째 cost:0.0001248160406248644, W:[1.0129445], b:[0.9705741]
1500번째 cost:2.9452479793690145e-05, W:[1.006288], b:[0.98570585]
1800번째 cost:6.949811449885601e-06, W:[1.0030545], b:[0.9930566]
2100번째 cost:1.6405671203756356e-06, W:[1.0014842], b:[0.99662644]
2400번째 cost:3.877670167184988e-07, W:[1.0007215], b:[0.99835974]
2700번째 cost:9.195375838544351e-08, W:[1.0003517], b:[0.99920154]
3000번째 cost:2.1877164968486795e-08, W:[1.0001713], b:[0.99961054]
3300번째 cost:5.241342027062501e-09, W:[1.0000837], b:[0.99980927]
3600번째 cost:1.2951772987435106e-09, W:[1.0000414], b:[0.9999051]
3900번째 cost:3.013080063229978e-10, W:[1.0000201], b:[0.99995434]
4200번째 cost:8.964562425717304e-11, W:[1.0000112], b:[0.9999752]
4500번째 cost:5.328478283606053e-11, W:[

In [5]:
# 최종적으로 나온 회귀식 H = W*x + b
W_, b_ = sess.run([w, b])





In [97]:
W_, b_

(array([1.4276195], dtype=float32), array([1.0000248], dtype=float32))

In [98]:
def predict(x):
    return W_[0] * x + b_[0]

In [99]:
predict(5)

8.138122081756592

## 2.2 predict을 위한 palceholder 이용
- placeholder : 외부에서 데이터를 입력받을 수 있는 노드

In [100]:
x = tf.placeholder(dtype=tf.float32)
H = 1*x + 1
sess = tf.Session()
sess.run([x, H], feed_dict={x : np.array([40,50])})

[array([40., 50.], dtype=float32), array([41., 51.], dtype=float32)]

In [101]:
# tensor 그래프 정의
# 데이터 셋 확보

x_data = np.array([1,2,3])
y_data = np.array([2,3,4])
# placeholder 설정(x, y)
x = tf.placeholder(dtype = tf.float32)
y = tf.placeholder(dtype = tf.float32)
# weight와 bias
W = tf.Variable(tf.random.normal([1]), name = 'weight')
b = tf.Variable(tf.random.normal([1]), name = 'bias')
# Hat, Hypothesis : 결과는 numpy 배열
H = W * x + b
# cost function (손실함수 : mse)
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w, b를 찾는 것
cost 함수는 2차함수이므로 곡선 그래프. 곡선위 미분값이 0이 되는 방향
(경사하강법GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# 세션 생성
sess = tf.Session()
# W,b 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습 (v2 에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b],
                                        feed_dict={x:x_data,
                                                  y:y_data})
    if step%300==0:
        print("{}번째 cost:{}, W:{}, b:{}".format(step, cost_val, W_val, b_val))


0번째 cost:0.706351101398468, W:[0.6119684], b:[1.0982342]
300번째 cost:0.0017269141972064972, W:[0.9518511], b:[1.1094537]
600번째 cost:0.0004074718744959682, W:[0.9766116], b:[1.0531672]
900번째 cost:9.614714508643374e-05, W:[0.9886389], b:[1.0258265]
1200번째 cost:2.2685946532874368e-05, W:[0.9944814], b:[1.0125451]
1500번째 cost:5.353325377654983e-06, W:[0.9973192], b:[1.0060941]
1800번째 cost:1.2634253607757273e-06, W:[0.9986977], b:[1.0029604]
2100번째 cost:2.9837923420927837e-07, W:[0.9993672], b:[1.0014386]
2400번째 cost:7.057716544522918e-08, W:[0.9996922], b:[1.0006998]
2700번째 cost:1.680960259875519e-08, W:[0.9998496], b:[1.0003413]
3000번째 cost:4.095549233085194e-09, W:[0.99992615], b:[1.0001684]
3300번째 cost:9.91595583421656e-10, W:[0.9999636], b:[1.0000827]
3600번째 cost:2.665766773990441e-10, W:[0.9999811], b:[1.0000433]
3900번째 cost:8.710306781400945e-11, W:[0.9999891], b:[1.0000248]
4200번째 cost:8.710306781400945e-11, W:[0.9999891], b:[1.0000248]
4500번째 cost:8.710306781400945e-11, W:[0.9999891

In [102]:
# 예측하기
sess.run(H, feed_dict={x:5})

array([5.9999704], dtype=float32)

## 2.3 scale이 다른 데이터들의 회귀분석 구현(scale 조정X)

In [103]:

x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))
# Hypothesis
H = W * x + b
# cost (손실함수)
cost = tf.reduce_mean(tf.square(H-y))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.0001)
train = optimizer.minimize(cost)
# Session & 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1, 6001):
    _, cost_val = sess.run([train, cost], feed_dict={x:x_data, y:y_data})
    if step%300==0:
        print("{}/6000번째 cost:{}".format(step+1, cost_val))





301/6000번째 cost:109.69410705566406
601/6000번째 cost:79.78150177001953
901/6000번째 cost:79.51172637939453
1201/6000번째 cost:79.49655151367188
1501/6000번째 cost:79.4839859008789
1801/6000번째 cost:79.47188568115234
2101/6000번째 cost:79.46022033691406
2401/6000번째 cost:79.44895935058594
2701/6000번째 cost:79.43807983398438
3001/6000번째 cost:79.4276351928711
3301/6000번째 cost:79.41754150390625
3601/6000번째 cost:79.40777587890625
3901/6000번째 cost:79.39836120605469
4201/6000번째 cost:79.38926696777344
4501/6000번째 cost:79.38050842285156
4801/6000번째 cost:79.3720474243164
5101/6000번째 cost:79.36388397216797
5401/6000번째 cost:79.35601043701172
5701/6000번째 cost:79.34844207763672
6001/6000번째 cost:79.34110260009766


## 2.4 scale이 다른 데이터들의 회귀분석 구현(scale 조정O)
### scale 조정 방법: 모든 데이터를 일정범위내로 조정
- normalization(정규화) : 모든 데이터를 - 0~1 사이로 조정
                    X - Xmin
- normalization =  _______________________
                    Xmax - Xmin

    * 위의 식을 써도 되지만 라이브러리 추천 (sklearn.preprocessing.MinMaxScaler)를 주로 씀
- standarization(표준화) : 데이터의 평균을 0, 표준편차를 1로 조정
                             X - Xmean
    standarization   =      _________
                            Xstd(표준편차)
                            
     *위의 식보다 라이브러리 추천(sklearn.preprocessing.StandardScaler)

In [104]:

# 라이브러리 쓰지 않고 정규화
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# x_data.min(), x_data.max(), x_data.mean(), x_data.std()
norm_scaled_x_data = (x_data - x_data.min()) / (x_data.max() - x_data.min())
norm_scaled_y_data = (y_data - y_data.min()) / (y_data.max() - y_data.min())

In [105]:

# 라이브러리를 사용하여 정규화
x_data = np.array([1, 2, 5, 8, 10]).reshape(-1,1)
y_data = np.array([5, 15, 68, 80, 95]).reshape(-1,1)
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler() # 독립변수 x를 정규화시킬 객체
scaler_x.fit(x_data)
norm_scaled_x_data = scaler_x.transform(x_data)
scaler_y = MinMaxScaler() # 종속(타겟)변수 y를 정규화시킬 객체
norm_scaled_y_data = scaler_y.fit_transform(y_data)
norm_scaled_y_data

array([[0.        ],
       [0.11111111],
       [0.7       ],
       [0.83333333],
       [1.        ]])

In [106]:
# 라이브러리를 쓰지 않고 표준화
x_data = np.array([1,2,5,8,10])
y_data = np.array([5,15,68,80,95])
stan_scaled_x_data = (x_data - x_data.mean()) / x_data.std()
stan_scaled_y_data = (y_data - y_data.mean()) / y_data.std()
np.column_stack([x_data, norm_scaled_x_data, stan_scaled_x_data])

array([[ 1.        ,  0.        , -1.22474487],
       [ 2.        ,  0.11111111, -0.93313895],
       [ 5.        ,  0.44444444, -0.05832118],
       [ 8.        ,  0.77777778,  0.81649658],
       [10.        ,  1.        ,  1.39970842]])

In [107]:
np.column_stack([y_data, norm_scaled_y_data, stan_scaled_y_data])

array([[ 5.        ,  0.        , -1.32373476],
       [15.        ,  0.11111111, -1.04563922],
       [68.        ,  0.7       ,  0.42826713],
       [80.        ,  0.83333333,  0.76198177],
       [95.        ,  1.        ,  1.17912508]])

In [108]:

# 라이브러리를 사용하여 표준화
x_data = np.array([1, 2, 5, 8, 10]).reshape(-1,1)
y_data = np.array([5, 15, 68, 80, 95]).reshape(-1,1)


from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
stan_scaled_x_data = scaler_x.fit_transform(x_data)
scaler_y = StandardScaler()
stan_scaled_y_data = scaler_y.fit_transform(y_data)



In [109]:
# 스케일 조정된 데이터를 다시 복구 : inverse_transform() 이용
scaler_y.inverse_transform(stan_scaled_y_data)

array([[ 5.],
       [15.],
       [68.],
       [80.],
       [95.]])

In [112]:
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))
# Hypothesis
H = W * x + b
# cost (손실함수)
cost = tf.reduce_mean(tf.square(H-y))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.0001)
train = optimizer.minimize(cost)
# Session & 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1, 6001):
    _, cost_val = sess.run([train, cost], feed_dict={x:norm_scaled_x_data, y:norm_scaled_y_data})
    if step%300==0:
        print("{}/6000번째 cost:{}".format(step, cost_val))

300/6000번째 cost:0.13268336653709412
600/6000번째 cost:0.11732101440429688
900/6000번째 cost:0.10406903922557831
1200/6000번째 cost:0.0926351398229599
1500/6000번째 cost:0.08276684582233429
1800/6000번째 cost:0.07424682378768921
2100/6000번째 cost:0.06688812375068665
2400/6000번째 cost:0.06052955985069275
2700/6000번째 cost:0.05503267049789429
3000/6000번째 cost:0.05027797818183899
3300/6000번째 cost:0.04616265371441841
3600/6000번째 cost:0.04259807989001274
3900/6000번째 cost:0.03950809687376022
4200/6000번째 cost:0.03682703897356987
4500/6000번째 cost:0.034498341381549835
4800/6000번째 cost:0.03247334808111191
5100/6000번째 cost:0.030710145831108093
5400/6000번째 cost:0.029172614216804504
5700/6000번째 cost:0.02782968059182167
6000/6000번째 cost:0.026654576882719994
