In [47]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:70% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:22pt;}
div.text_cell_render.rendered_html{font-size:18pt;}
div.text_cell_render ul li{font-size:22pt; line-height:30px;}
div.output {font-size:22pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:22pt;}
div.prompt {min-width:40px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:22pt;padding:5px;}
table.dataframe{font-size:22px;}
</style>
"""))

# 1. 데이터 셋


In [4]:
import pandas as pd
df = pd.read_csv('data/ch13_df(결측치중위값으로대체).csv')
df.head()

지역명   평당분양가격    연도   월
0  서울  18189.0  2013  12
1  부산   8111.0  2013  12
2  대구   8080.0  2013  12
3  인천  10204.0  2013  12
4  광주   6098.0  2013  12

In [5]:
df

지역명   평당분양가격    연도   월
0     서울  18189.0  2013  12
1     부산   8111.0  2013  12
2     대구   8080.0  2013  12
3     인천  10204.0  2013  12
4     광주   6098.0  2013  12
...   ..      ...   ...  ..
2171  전북  12058.2  2024   8
2172  전남  13120.8  2024   8
2173  경북  13827.0  2024   8
2174  경남  13252.8  2024   8
2175  제주  25419.9  2024   8

[2176 rows x 4 columns]

지역명2 : 지역명필드를 라벨인코딩하여 추가
독립변수 : 지역명2, 연도, 월
타겟변수 : 평당분양가격
독립변수와 타겟변수의 스케일 조정
정규화(MinMaxScaler) 작업후 : 지역명2m, 연도m, 월m
표준화(StandardScaler) 작업후 : 지역명2s, 연도s, 월s => 지역명, 연도, 월, 지역명2, 지역명2m, 연도m, 월m, 지역명2s, 연도s, 월s


In [6]:
from tensorflow.keras.utils import to_categorical

# 2. 지역명의 라벨인코딩
-지역명2

In [7]:
X = df[['지역명']].values

In [8]:
from sklearn.preprocessing import LabelEncoder


X_flat = X.ravel() 

le = LabelEncoder()
labeling_data = le.fit_transform(X_flat)

print('라벨인코딩된 데이터 :', labeling_data)

라벨인코딩된 데이터 : [ 8  7  5 ...  3  2 14]


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['지역명2'] = le.fit_transform(df['지역명']) # 문자데이터를 가나다순으로 정렬후 숫자로 변환
df.head()

지역명   평당분양가격    연도   월  지역명2     지역명2s       연도s       월s
0  서울  18189.0  2013  12     8  0.000000 -1.875367  1.62196
1  부산   8111.0  2013  12     7 -0.204124 -1.875367  1.62196
2  대구   8080.0  2013  12     5 -0.612372 -1.875367  1.62196
3  인천  10204.0  2013  12    11  0.612372 -1.875367  1.62196
4  광주   6098.0  2013  12     4 -0.816497 -1.875367  1.62196

In [9]:
df['지역명2'] = labeling_data

# 3. MinMaxScale조정


In [24]:
X_data = df[['지역명2', '연도','월']].values # numpy배열로 추출한 독립변수
# values나 to_numpy()를 이용해서 데이터프레임을 numpy배열로 변환
y_data = df[['평당분양가격']].to_numpy() 
X_data.shape, y_data.shape




((2176, 3), (2176, 1))

In [25]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()
df[['지역명2m', '연도m','월m']] = scaler_x.fit_transform(X_data)
df[['평당분양가격m']] = scaler_y.fit_transform(y_data)
df.head()

지역명   평당분양가격    연도   월  지역명2     지역명2s       연도s       월s   지역명2m  연도m   월m  \
0  서울  18189.0  2013  12     8  0.000000 -1.875367  1.62196  0.5000  0.0  1.0   
1  부산   8111.0  2013  12     7 -0.204124 -1.875367  1.62196  0.4375  0.0  1.0   
2  대구   8080.0  2013  12     5 -0.612372 -1.875367  1.62196  0.3125  0.0  1.0   
3  인천  10204.0  2013  12    11  0.612372 -1.875367  1.62196  0.6875  0.0  1.0   
4  광주   6098.0  2013  12     4 -0.816497 -1.875367  1.62196  0.2500  0.0  1.0   

    평당분양가격m  
0  0.328198  
1  0.065274  
2  0.064466  
3  0.119878  
4  0.012757

In [17]:
y_data

array([[18189. ],
       [ 8111. ],
       [ 8080. ],
       ...,
       [13827. ],
       [13252.8],
       [25419.9]])

In [35]:
# import pandas as pd
# from sklearn.preprocessing import LabelEncoder, MinMaxScaler

# scaler = MinMaxScaler()


# df[['지역명2m', '연도m', '월m']] = scaler.fit_transform(df[['지역명2', '연도', '월']])


# print(df)

In [30]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

df[['지역명2m', '연도m', '월m']] = scaler_x.fit_transform(X_data)
df[["평당분양가격m"]]  = scaler_y.fit_transform(y_data)

In [31]:
import tabulate
from tabulate import tabulate

print(tabulate(df.head(10), headers='keys', tablefmt='grid', showindex=False))

+----------+----------------+--------+------+-----------+------------+----------+---------+------------+---------+-------+-----------------+
| 지역명   |   평당분양가격 |   연도 |   월 |   지역명2 |   지역명2s |    연도s |     월s |   지역명2m |   연도m |   월m |   평당분양가격m |
+==========+================+========+======+===========+============+==========+=========+============+=========+=======+=================+
| 서울     |          18189 |   2013 |   12 |         8 |   0        | -1.87537 | 1.62196 |     0.5    |       0 |     1 |       0.328198  |
+----------+----------------+--------+------+-----------+------------+----------+---------+------------+---------+-------+-----------------+
| 부산     |           8111 |   2013 |   12 |         7 |  -0.204124 | -1.87537 | 1.62196 |     0.4375 |       0 |     1 |       0.0652744 |
+----------+----------------+--------+------+-----------+------------+----------+---------+------------+---------+-------+-----------------+
| 대구     |           8080 |   2013 |   12 |       

# 4. standardScale 조정

In [39]:
# import pandas as pd
# from sklearn.preprocessing import LabelEncoder, StandardScaler


# scaler = StandardScaler()


# df[['지역명2s', '연도s', '월s']] = scaler.fit_transform(df[['지역명2', '연도', '월']])
# df[['평당분양가격m']] = scaler.fit_transform(df[[y_data]])



# print(df)

In [43]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = StandardScaler()
scaler_y = StandardScaler()

df[['지역명s', '연도s', '월s']] = scaler_x.fit_transform(X_data)
df[["평당분양가격s"]]  = scaler_y.fit_transform(y_data)

df.head()

지역명   평당분양가격    연도   월  지역명2     지역명2s       연도s       월s     지역명2m  \
0  서울  18189.0  2013  12     8  0.000000 -1.875367  1.62196  0.000000   
1  부산   8111.0  2013  12     7 -0.204124 -1.875367  1.62196 -0.204124   
2  대구   8080.0  2013  12     5 -0.612372 -1.875367  1.62196 -0.612372   
3  인천  10204.0  2013  12    11  0.612372 -1.875367  1.62196  0.612372   
4  광주   6098.0  2013  12     4 -0.816497 -1.875367  1.62196 -0.816497   

        연도m       월m   평당분양가격m      지역명s   평당분양가격s  
0 -1.875367  1.62196  1.168591  0.000000  1.168591  
1 -1.875367  1.62196 -0.728312 -0.204124 -0.728312  
2 -1.875367  1.62196 -0.734147 -0.612372 -0.734147  
3 -1.875367  1.62196 -0.334363  0.612372 -0.334363  
4 -1.875367  1.62196 -1.107203 -0.816497 -1.107203

# 5. 지역명을 원핫인코딩
- 강원 0 > 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
- 서울 0 > 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0

In [50]:
df.loc[:16,['지역명', '지역명2']].sort_values(by='지역명2')

지역명  지역명2
9   강원     0
7   경기     1
15  경남     2
14  경북     3
4   광주     4
2   대구     5
5   대전     6
1   부산     7
0   서울     8
8   세종     9
6   울산    10
3   인천    11
13  전남    12
12  전북    13
16  제주    14
11  충남    15
10  충북    16

In [45]:
# print(tabulate(df.head(10), headers='keys', tablefmt='grid', showindex=False))

In [54]:
loc = df.loc[:16,['지역명', '지역명2']].sort_values(by='지역명2')['지역명'].tolist()
print(loc) # 원핫인코딩 후 열이름

['강원', '경기', '경남', '경북', '광주', '대구', '대전', '부산', '서울', '세종', '울산', '인천', '전남', '전북', '제주', '충남', '충북']


In [69]:
from tensorflow.keras.utils import to_categorical
import pandas as pd
import numpy as np
temp1 = temp1 = to_categorical(df['지역명2'])
temp2 = pd.get_dummies(df['지역명']).values
# to_categorical()결과는 numpy 배열, 최대정수가 16이면 0~16카테고리로 원핫인코딩

In [70]:

# pd.get_dummies()결과는 데이터프레임,
# 정수가 곧 카테고리가 되서 원핫인코딩, 매개변수에 문자(라벨인코딩된 값)

In [71]:
np.all(temp1 == temp2)

True

In [72]:
temp1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [73]:
temp2

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=uint8)

In [75]:
pd.options.display.max_columns = 30

In [79]:
df[loc] = to_categorical(df['지역명2'])#.astype(np.int16)
pd.options.display.max_columns = 30
df[loc].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2176 entries, 0 to 2175
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   강원      2176 non-null   float32
 1   경기      2176 non-null   float32
 2   경남      2176 non-null   float32
 3   경북      2176 non-null   float32
 4   광주      2176 non-null   float32
 5   대구      2176 non-null   float32
 6   대전      2176 non-null   float32
 7   부산      2176 non-null   float32
 8   서울      2176 non-null   float32
 9   세종      2176 non-null   float32
 10  울산      2176 non-null   float32
 11  인천      2176 non-null   float32
 12  전남      2176 non-null   float32
 13  전북      2176 non-null   float32
 14  제주      2176 non-null   float32
 15  충남      2176 non-null   float32
 16  충북      2176 non-null   float32
dtypes: float32(17)
memory usage: 144.6 KB


In [78]:
df[loc] = df[loc].astype(np.int16)
df.head()

지역명   평당분양가격    연도   월  지역명2     지역명2s       연도s       월s     지역명2m  \
0  서울  18189.0  2013  12     8  0.000000 -1.875367  1.62196  0.000000   
1  부산   8111.0  2013  12     7 -0.204124 -1.875367  1.62196 -0.204124   
2  대구   8080.0  2013  12     5 -0.612372 -1.875367  1.62196 -0.612372   
3  인천  10204.0  2013  12    11  0.612372 -1.875367  1.62196  0.612372   
4  광주   6098.0  2013  12     4 -0.816497 -1.875367  1.62196 -0.816497   

        연도m       월m   평당분양가격m      지역명s   평당분양가격s  강원  ...  경남  경북  광주  대구  \
0 -1.875367  1.62196  1.168591  0.000000  1.168591   0  ...   0   0   0   0   
1 -1.875367  1.62196 -0.728312 -0.204124 -0.728312   0  ...   0   0   0   0   
2 -1.875367  1.62196 -0.734147 -0.612372 -0.734147   0  ...   0   0   0   1   
3 -1.875367  1.62196 -0.334363  0.612372 -0.334363   0  ...   0   0   0   0   
4 -1.875367  1.62196 -1.107203 -0.816497 -1.107203   0  ...   0   0   1   0   

   대전  부산  서울  세종  울산  인천  전남  전북  제주  충남  충북  
0   0   0   1   0   0   0   0   0   0   0   0  
1   0   1   0   0   0   0   0   0   0   0   0  
2   0   0   0   0   0   0   0   0   0   0   0  
3   0   0   0   0   0   1   0   0   0   0   0  
4   0   0   0   0   0   0   0   0   0   0   0  

[5 rows x 31 columns]

In [81]:
df[loc] = pd.get_dummies(df['지역명2'])
df.head(1)

지역명   평당분양가격    연도   월  지역명2  지역명2s       연도s       월s  지역명2m       연도m  \
0  서울  18189.0  2013  12     8    0.0 -1.875367  1.62196    0.0 -1.875367   

        월m   평당분양가격m  지역명s   평당분양가격s  강원  ...  경남  경북  광주  대구  대전  부산  서울  세종  \
0  1.62196  1.168591   0.0  1.168591   0  ...   0   0   0   0   0   0   1   0   

   울산  인천  전남  전북  제주  충남  충북  
0   0   0   0   0   0   0   0  

[1 rows x 31 columns]

In [84]:
# 원핫인코딩 데이터 지우기
df.drop(loc, axis=1)
df.head(1)

지역명   평당분양가격    연도   월  지역명2  지역명2s       연도s       월s  지역명2m       연도m  \
0  서울  18189.0  2013  12     8    0.0 -1.875367  1.62196    0.0 -1.875367   

        월m   평당분양가격m  지역명s   평당분양가격s  강원  ...  경남  경북  광주  대구  대전  부산  서울  세종  \
0  1.62196  1.168591   0.0  1.168591   0  ...   0   0   0   0   0   0   1   0   

   울산  인천  전남  전북  제주  충남  충북  
0   0   0   0   0   0   0   0  

[1 rows x 31 columns]

In [86]:
# 원핫인코딩 방법3
pd.concat([df, pd.get_dummies(df['지역명'])], axis=1)
df.sample(2)

지역명   평당분양가격    연도  월  지역명2     지역명2s       연도s        월s     지역명2m  \
1744  충북   9906.6  2022  7    16  1.632993  1.020642  0.174185  1.632993   
925   울산  10312.5  2018  7    10  0.408248 -0.266473  0.174185  0.408248   

           연도m        월m   평당분양가격m      지역명s   평당분양가격s  강원  ...  경남  경북  광주  \
1744  1.020642  0.174185 -0.390340  1.632993 -0.390340   0  ...   0   0   0   
925  -0.266473  0.174185 -0.313941  0.408248 -0.313941   0  ...   0   0   0   

      대구  대전  부산  서울  세종  울산  인천  전남  전북  제주  충남  충북  
1744   0   0   0   0   0   0   0   0   0   0   0   1  
925    0   0   0   0   0   1   0   0   0   0   0   0  

[2 rows x 31 columns]

In [87]:
df = df.drop(loc, axis=1)
df.head(1)

지역명   평당분양가격    연도   월  지역명2  지역명2s       연도s       월s  지역명2m       연도m  \
0  서울  18189.0  2013  12     8    0.0 -1.875367  1.62196    0.0 -1.875367   

        월m   평당분양가격m  지역명s   평당분양가격s  
0  1.62196  1.168591   0.0  1.168591